# Datei: webserver/traefik/me/docker-compose.yml
version: '3'
services:
  test:
    image: nginx:1
    networks:
      - default
      - web
    labels:
      - traefik.http.routers.test.rule=Host(`me.dockertest.info`)
      - traefik.http.routers.test.tls=true
      - traefik.http.routers.test.tls.certresolver=lets-encrypt
      - traefik.http.services.test.loadbalancer.server.port=80
networks:
  web:
    external: true
