# Datei: webserver/node-express/docker-compose.yml
version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: docker/node-express:dev
    volumes:
      - ./src:/src
      - node_exp_modules:/src/node_modules
    ports:
      - 8080:3000
    environment:
      DEBUG: "src"
    command: [ "nodemon", "bin/www" ]
volumes:
  node_exp_modules:
